# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addnew.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddTask(object):
    def setupUi(self, AddTask):
        AddTask.setObjectName("AddTask")
        AddTask.resize(1084, 625)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AddTask.sizePolicy().hasHeightForWidth())
        AddTask.setSizePolicy(sizePolicy)
        AddTask.setMaximumSize(QtCore.QSize(1084, 625))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        AddTask.setFont(font)
        AddTask.setAutoFillBackground(False)
        AddTask.setStyleSheet("background-color: rgb(189, 215, 238);\n"
"border-color: rgb(170, 170, 255);")
        self.centralwidget = QtWidgets.QWidget(AddTask)
        self.centralwidget.setObjectName("centralwidget")
        self.TitleBack = QtWidgets.QFrame(self.centralwidget)
        self.TitleBack.setGeometry(QtCore.QRect(0, -10, 1091, 91))
        self.TitleBack.setStyleSheet("background-color: rgb(91, 155, 213);")
        self.TitleBack.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TitleBack.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TitleBack.setObjectName("TitleBack")
        self.TitleBack2 = QtWidgets.QFrame(self.TitleBack)
        self.TitleBack2.setGeometry(QtCore.QRect(40, 20, 1002, 62))
        self.TitleBack2.setStyleSheet("border-color: rgb(0, 0, 0);\n"
"background-color: rgb(255, 255, 255);")
        self.TitleBack2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.TitleBack2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.TitleBack2.setObjectName("TitleBack2")
        self.Title = QtWidgets.QLabel(self.TitleBack2)
        self.Title.setGeometry(QtCore.QRect(440, 10, 121, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.AddTaskBtn = QtWidgets.QPushButton(self.centralwidget)
        self.AddTaskBtn.setGeometry(QtCore.QRect(740, 490, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.AddTaskBtn.setFont(font)
        self.AddTaskBtn.setStyleSheet("background-color: rgb(91, 155, 213);\n"
"color: rgb(255, 255, 255);")
        self.AddTaskBtn.setObjectName("AddTaskBtn")
        self.CancelBtn = QtWidgets.QPushButton(self.centralwidget)
        self.CancelBtn.setGeometry(QtCore.QRect(920, 490, 131, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.CancelBtn.setFont(font)
        self.CancelBtn.setStyleSheet("background-color: rgb(91, 155, 213);\n"
"color: rgb(255, 255, 255);")
        self.CancelBtn.setObjectName("CancelBtn")
        self.TaskName = QtWidgets.QLabel(self.centralwidget)
        self.TaskName.setGeometry(QtCore.QRect(30, 130, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.TaskName.setFont(font)
        self.TaskName.setObjectName("TaskName")
        self.NameBox = QtWidgets.QLineEdit(self.centralwidget)
        self.NameBox.setGeometry(QtCore.QRect(170, 145, 611, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.NameBox.setFont(font)
        self.NameBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.NameBox.setObjectName("NameBox")
        self.DueDate = QtWidgets.QLabel(self.centralwidget)
        self.DueDate.setGeometry(QtCore.QRect(30, 230, 141, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.DueDate.setFont(font)
        self.DueDate.setObjectName("DueDate")
        self.DateDayBox = QtWidgets.QLineEdit(self.centralwidget)
        self.DateDayBox.setGeometry(QtCore.QRect(170, 245, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.DateDayBox.setFont(font)
        self.DateDayBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DateDayBox.setObjectName("DateDayBox")
        self.EstTime = QtWidgets.QLabel(self.centralwidget)
        self.EstTime.setGeometry(QtCore.QRect(30, 330, 291, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.EstTime.setFont(font)
        self.EstTime.setObjectName("EstTime")
        self.TimeBox = QtWidgets.QLineEdit(self.centralwidget)
        self.TimeBox.setGeometry(QtCore.QRect(320, 345, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.TimeBox.setFont(font)
        self.TimeBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.TimeBox.setObjectName("TimeBox")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(430, 330, 81, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label1.setFont(font)
        self.label1.setObjectName("label1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(280, 230, 31, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label2.setFont(font)
        self.label2.setObjectName("label2")
        self.DateMonthBox = QtWidgets.QLineEdit(self.centralwidget)
        self.DateMonthBox.setGeometry(QtCore.QRect(300, 245, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.DateMonthBox.setFont(font)
        self.DateMonthBox.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DateMonthBox.setObjectName("DateMonthBox")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(410, 230, 31, 71))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.label3.setFont(font)
        self.label3.setObjectName("label3")
        self.DateMonthBox_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.DateMonthBox_2.setGeometry(QtCore.QRect(430, 245, 100, 40))
        font = QtGui.QFont()
        font.setFamily("Calibri")
        font.setPointSize(14)
        self.DateMonthBox_2.setFont(font)
        self.DateMonthBox_2.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.DateMonthBox_2.setObjectName("DateMonthBox_2")
        AddTask.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(AddTask)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1084, 18))
        self.menubar.setObjectName("menubar")
        AddTask.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(AddTask)
        self.statusbar.setObjectName("statusbar")
        AddTask.setStatusBar(self.statusbar)

        self.retranslateUi(AddTask)
        QtCore.QMetaObject.connectSlotsByName(AddTask)

    def retranslateUi(self, AddTask):
        _translate = QtCore.QCoreApplication.translate
        AddTask.setWindowTitle(_translate("AddTask", "MainWindow"))
        self.Title.setText(_translate("AddTask", "Add Task"))
        self.AddTaskBtn.setText(_translate("AddTask", "Add Task"))
        self.CancelBtn.setText(_translate("AddTask", "Cancel"))
        self.TaskName.setText(_translate("AddTask", "Task Name:"))
        self.DueDate.setText(_translate("AddTask", "Due Date:"))
        self.EstTime.setText(_translate("AddTask", "Estimated Time Needed:"))
        self.label1.setText(_translate("AddTask", "Hours"))
        self.label2.setText(_translate("AddTask", "/"))
        self.label3.setText(_translate("AddTask", "/"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddTask = QtWidgets.QMainWindow()
    ui = Ui_AddTask()
    ui.setupUi(AddTask)
    AddTask.show()
    sys.exit(app.exec_())
